name: "Generate screenshoot last post DEV.TO"
on:
  schedule:
  - cron: "*/50 * * * *"

jobs:
  takeScreenshoot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install packages
      run: npm i

    - name: Set envs
      run: |
        echo "" > .env
        echo "DEVTO_USERNAME='tiago123456789'" >> .env
        echo "PATH_SCREENSHOOT='./last-article-devto.png'" >> .env
        echo "GITHUB_REPOSITORY='tiago123456789'" >> .env
        echo "GITHUB_USERNAME='tiago123456789'" >> .env
        echo "FILE_TO_UPLOAD='last-article-devto.png'" >> .env
        echo "GITHUB_TOKEN='{{ secrets.G_TOKEN }}'" >> .env
        echo "BROWSERLESS_TOKEN='{{ secrets.BROWSERLESS_TOKEN }}'" >> .env

    - name: Execute script
      run: node index.js
